### ISSUE TITLE
gcc 10 fails with - multiple definition of `light_loglevel'

### ISSUE THREAD

**Issue by FrostyX** [haikarainen/light#107]
There is a problem with building `light` using gcc 10.

    make[2]: Leaving directory '/builddir/build/BUILD/light-1.2.1/src'
    /usr/bin/ld: light-light.o:/builddir/build/BUILD/light-1.2.1/src/helpers.h:24: multiple definition of 
    `light_loglevel'; light-main.o:/builddir/build/BUILD/light-1.2.1/src/helpers.h:24: first defined here
    /usr/bin/ld: light-helpers.o:/builddir/build/BUILD/light-1.2.1/src/helpers.h:24: multiple definition of 
    `light_loglevel'; light-main.o:/builddir/build/BUILD/light-1.2.1/src/helpers.h:24: first defined here
    /usr/bin/ld: impl/light-sysfs.o:/builddir/build/BUILD/light-1.2.1/src/./helpers.h:24: multiple definition of `light_loglevel'; light-main.o:/builddir/build/BUILD/light-1.2.1/src/helpers.h:24: first defined here
    /usr/bin/ld: impl/light-util.o:/builddir/build/BUILD/light-1.2.1/src/./helpers.h:24: multiple definition of 
    `light_loglevel'; light-main.o:/builddir/build/BUILD/light-1.2.1/src/helpers.h:24: first defined here
    /usr/bin/ld: impl/light-razer.o:/builddir/build/BUILD/light-1.2.1/src/./helpers.h:24: multiple definition of `light_loglevel'; light-main.o:/builddir/build/BUILD/light-1.2.1/src/helpers.h:24: first defined here

We discovered this issue in Fedora rawhide - https://bugzilla.redhat.com/show_bug.cgi?id=1799609
It is caused by having `-fno-common` as a default in gcc 10.
I workarounded it in downstream with this patch 

https://src.fedoraproject.org/rpms/light/c/c64f33fc338e599e94b2427bdb17a88cdeab6163?branch=master

but I guess this should be properly fixed in the source code.

**Comment by MarcinWieczorek** [comment]
Great job. Any update on this?

**Comment by FrostyX** [comment]
> Great job. Any update on this?

Not from my side, I don't know C that well. @haikarainen ?

**Comment by haikarainen** [comment]
> Great job. Any update on this?

Sorry, I dont really have much time for this project. Feel free to do a PR. The code in question has itched me for quite some time lol.

**Comment by yutakatay** [comment]
https://github.com/haikarainen/light/pull/114
