### ISSUE TITLE
Fading between brightness changes

### ISSUE THREAD

**Issue by davcri** [haikarainen/light#11]
The fading feature of xbacklight is very pleasent to the eye. 
Will `light` have something similar in the future ?

**Comment by haikarainen** [comment]
@davcri Probably not. It would require a daemon to run smoothly, and right now `light` is a very minimal, low-level application to simply set a value and exit.

If I ever were to implement it, I would probably add a switch to run light in daemon mode on a preselected controler, which simply listens for and executes commands on said controller, and then implement another executable `lightctl` to send commands to this daemon.

If anyone wanna create a pull request for this functionality, this is how I would prefer it to be implemented, however suggestions are always welcome. Bonuspoints if you manage to implement a client plugin to have the screen light up in sync to music.

**Comment by haikarainen** [comment]
(leaving this open for suggestions and peer review, just in case)

**Comment by davcri** [comment]
If I understood well you would like to have a client that sends multiple commands in order to create the fade effect?

**Comment by haikarainen** [comment]
@davcri  close but not quite.

`lightctl` would simply send one command, `set brightness to 20%` for example.

`light` would then receive this command in a thread specially made for receiving commands, and set a variable `target-brightness` to 20%.

In a completely separate thread, `light` is managing the actual backlight brightness. It works in a continuous, infinite loop, where it writes the brightness value to the controller one step closer to `target-brightness`.  So every iteration of the loop it does something like:

```c
if(curr_brightness != target_brigthness)
{
  set_curr_brightness(mix(curr_brightness, target_brightness, 0.1))
}
```

This code would fade the light in an exponential manner (as opposed to linear fade), giving a smooth effect. If you would like linear, you would just increate the current brightness with a fixed value instead.

**Comment by mkoskar** [comment]
@haikarainen Why this can't be synchronous? Run the `light` and let it return after the target value got reached. Such animation will not take long anyway (usually), so possible race-conditions like running  second instance of `light` with different target value can be ignored or taken care of by `flock` on the target file, or e.g., `/run/user/1000/light.lock`.

**Comment by haikarainen** [comment]
@mkoskar that would create a very non-smooth user experience in practice. If you for example bind F11 to decrease brightness by 10%, and F12 to increase brightness by 10%, and then press either F11 or F12 faster than the previous `light` process takes to run, keypresses would simply be ignored (or delayed if you let the process wait until a lockfile can be opened).

**Comment by haikarainen** [comment]
I have decided to not implement this as I have too much on my plate atm. If someone is interested in implementing it, feel free to do a pull req. Just keep in mind to read the comments on this issue to get pointers on how I'd prefer it to be implemented first. Also keep in mind that ANSI C89 is mandatory even for new executables, and that added dependencies are frowned upon (unless theyre really worth it).
