### ISSUE TITLE
ubuntu 20: sudo issue

### ISSUE THREAD

**Issue by vlp-git** [haikarainen/light#113]
Hello,

First, thanks for your program !!

I am not able to run Light without sudo. I am into the video group but still unable to launch it.

Thanks !

vlp

**Comment by lbesnard** [comment]
same here. also tried input and lightdm without sucess

**Comment by haikarainen** [comment]
Verify that you can write to the controllers without light (/sys/class/backlight/*/brightness)

**Comment by lbesnard** [comment]
thanks, I had to do the following

```bash
sudo chgrp video /sys/class/backlight/*/brightness
sudo chmod 664 /sys/class/backlight/*/brightness
sudo usermod -a -G video $USER
```

**Comment by lbesnard** [comment]
actually this kind of works, but mint (or ubuntu) is resetting the permission on reboot.

**Comment by AhmedHalim96** [comment]
I'm on Linux Mint and this didn't work for me!
what did work for me  is declaring brightness_widget as a global variable and then adding brightness_widget:inc() and brightness_widget:dec() to the brightness keys

**Comment by haikarainen** [comment]
> I have this issue under Arch Linux as well.

Fix your systems permissions and it will work. There is no bug here.  There's not really much at all I can do about system permissions. Thinking about banning issues about permission errors, however they seem to help others from time to time.

**Comment by tgy** [comment]
I ended up using `brightnessctl`, which worked out-of-the-box, without having to mess with my system's permissions.
