### ISSUE TITLE
THIS PROJECT NEEDS A NEW FULL-TIME MAINTAINER

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/light#116]
As per the fine. all-caps title, this project needs a new maintainer. I don't have the time for this project at all these days, and it's really a shame because it's growing increasingly bigger by the day. New distributions adopt it, along with higher standards for security etc.

So, do you know C well? Do you want to adopt a project and call it your own? Drop a line in this thread!

**Comment by haikarainen** [comment]
@troglobit Thoughts?

**Comment by troglobit** [comment]
@haikarainen Sorry, I've switched to Linux Mint and Cinnamon across the board. No time.

**Comment by orhun** [comment]
Hmm interesting. Let me see the source code...

**Comment by haikarainen** [comment]
@orhun Your other repos look great! See DOCUMENTATION.md for some introduction to the project, let me know if you want to hop aboard!

https://github.com/haikarainen/light/blob/master/DOCUMENTATION.md

**Comment by jlevers** [comment]
@haikarainen I'm interested in taking this on -- I sent you an email with some questions/info at the email address on your website, but it bounced. Happy to talk about it anytime...my email is jesse \at jesseevers \dot com.

**Comment by haikarainen** [comment]
@jlevers You've got mail

**Comment by binex-dsk** [comment]
i would not mind maintaining this

**Comment by binex-dsk** [comment]
@haikarainen actually yeah, this seems great, I'd actually love to maintain this. WOuld maybe finally be a practical use of C for me finally, and it doesn't look too difficult. Plus I've got an idea or 2 for this

**Comment by PeterlitsZo** [comment]
Is the author alive :cry:?

**Comment by haikarainen** [comment]
> Is the author alive 😢?

Yes, I just have very limited time, as the post states lol.

**Comment by PeterlitsZo** [comment]
> > Is the author alive cry?
> 
> Yes, I just have very limited time, as the post states lol.

Well, I think I do not know a lot about linux / light / hardware and so on. But I'd like to help to make it better. I am in school and I have some time to learn it and help you.

**Comment by haikarainen** [comment]
> Well, I think I do not know a lot about linux / light / hardware and so on. But I'd like to help to make it better. I am in school and I have some time to learn it and help you.

While I appreciate your interest, this utility is pretty widely used in different Linux-based OS'es at this stage, and because of this, a new maintainer would need to be somewhat experienced, especially in the GNU/Linux ecosystem. That said, feel free to make pull requests and check out the open issues in this project.

**Comment by PeterlitsZo** [comment]
> > Well, I think I do not know a lot about linux / light / hardware and so on. But I'd like to help to make it better. I am in school and I have some time to learn it and help you.
> 
> While I appreciate your interest, this utility is pretty widely used in different Linux-based OS'es at this stage, and because of this, a new maintainer would need to be somewhat experienced, especially in the GNU/Linux ecosystem. That said, feel free to make pull requests and check out the open issues in this project.

Yes... You are right... I think so.

**Comment by PeterlitsZo** [comment]
Sad to hear that...
