### ISSUE TITLE
Adjust brightness by docker container

### ISSUE THREAD

**Issue by ahmed-tracxpoint** [haikarainen/light#117]
How can I adjust screen brightness from docker container?
 I tried from terminal it's working perfectly, but not working from container bash.

I should add devices or volumes in my docker-compose?

**Comment by haikarainen** [comment]
If you have a working sysfs system under what the environment perceives as `/sys`, and you have read/write permissions to `/sys/class/backlight` devices, it should work. 

I cant really answer any docker-related questions. Run light in verbose mode to get debug output (a message on what went wrong from light's perspective).

**Comment by ahmed-tracxpoint** [comment]
right this permission problems:
 
``` bash
helpers.c:21: Error: could not open '/etc/light/targets/sysfs/backlight/intel_backlight/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
helpers.c:45: Error: could not open '/sys/class/backlight/intel_backlight/brightness' for writing
helpers.c:45: Error: Verify it exists with the right permissions
impl/sysfs.c:133: Error: failed to write to sysfs device
light.c:695: Error: failed to write to target
main.c:20: Error: Execution failed
```
but also /etc/light is empty

**Comment by haikarainen** [comment]
Look up how to setup sysfs permissions in docker. Read README.md to find out how light may expect permissions to be setup.

/etc/light being empty is not a problem.

**Comment by ahmed-tracxpoint** [comment]
Thanks I just added **privileged: true** for docker-compose and it worked correctly.

I tried to run the container in another device and I had this error:
light.c:636: Warning: no such target, "auto"
No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.

impl/util.c:31: Notice: impl_util_dryrun_get: reading brightness (0) from utility target dryrun
impl/util.c:38: Notice: impl_util_dryrun_getmax: reading max. brightness (255) from utility target dryrun
0.00


and I cannot find the device in /sys/class/backlight/

**Comment by haikarainen** [comment]
Did you try reading and following the information in the output?

**Comment by ahmed-tracxpoint** [comment]
this happen when I tried to run in mint linux, this is the output for light cli

**Comment by haikarainen** [comment]
You didn't read, listen or answer to what I just wrote. The system in question probably lacks a backlight controller. Light only controls available controllers.

Please read the output of programs when you have issues with them. The answer is right there, clear as day. I'm helping you with this issue completely for free, the least I could ask in return is that you actually give a damn to try and resolve it yourself.

Locking this thread.
