### ISSUE TITLE
For increments in brightness percentage, an accumulating rounding error produces an unexpected result.

### ISSUE THREAD

**Issue by megaqzs** [haikarainen/light#127]
Demo:
[![asciicast](https://asciinema.org/a/BebWaGqactFdkA7YA6vnb4WtC.svg)](https://asciinema.org/a/BebWaGqactFdkA7YA6vnb4WtC)

**Comment by haikarainen** [comment]
This is expected behaviour and not really a bug. The accuracy of the controller is 256 levels of brightness (0-255). You add 10 percent each time, which in raw mode would be 25 (rounded down from 25.5). Add 6*25 and you get 150/255 = 0,5882 = 58.82%.
