### ISSUE TITLE
Support for keyboard backlight

### ISSUE THREAD

**Issue by sbmueller** [haikarainen/light#13]
Besides display backlight, it would be great to control keyboard backlight in the same manner. I can deal with this in a few weeks maybe.

**Comment by haikarainen** [comment]
That would be very cool. What kind of files does `/sys/class/led` have? It looks pretty similiar to backlight from here, but I'm not on a linux laptop atm.

Anyway, I would probably prefer it to function so that you'd add a new "target" parameter (read readme). Like a "-k" switch or something, that basically says "Do this operation on a LED instead of a backlight".

Thoughts?

**Comment by sbmueller** [comment]
`/sys/class/led` has the exact same structure as backlight :) I have quicksolved this whith two executables `light` and `kblight`. Maybe we can introduce additional flags -B (for backlight) and -K (for Keyboard) as a better solution. When nothing provided, use -B as default.

**Comment by haikarainen** [comment]
> /sys/class/led has the exact same structure as backlight 

Ah, then that makes it much easier!

> Maybe we can introduce additional flags -B (for backlight) and -K (for Keyboard) as a better solution. When nothing provided, use -B as default.

That would conflict with the current argument structure. Upper-caps flags are reserved for operation modes. I will probably add flags under the "target" group, `-l` or something. 

Will get on implementing this as soon as possible.

**Comment by haikarainen** [comment]
So I have just recently got my hands on a laptop with Linux (and leds!), so I will probably get on to implementing this in the following weeks.

**Comment by IbnSaeed** [comment]
Any update ?

**Comment by haikarainen** [comment]
No sorry.

**Comment by IbnSaeed** [comment]
ok

**Comment by haikarainen** [comment]
Feel free to implement it yourself. Should be rather easy. I dont really
have time at all for hobby stuff anymore, 3 kids and a fulltime programming
job :(

**Comment by IbnSaeed** [comment]
no problem.
