### ISSUE TITLE
Install by build: Configure file missing

### ISSUE THREAD

**Issue by lamyergeier** [haikarainen/light#131]
It is mentioned in the readme that

If you download a stable release, these are the commands that will get you up and running:

```
tar xf light-x.yy.tar.gz
cd light-x.yy/
./configure && make
sudo make install
```

./configure does not exists in the latest  release!

**Comment by PeterlitsZo** [comment]
See https://github.com/haikarainen/light#manual

> However the latest development branch requires some extras. Clone the repository and run the autogen.sh script. This requires that automake and autoconf is installed on your system.
> ...

**Comment by PeterlitsZo** [comment]
I hope it helps you.

**Comment by haikarainen** [comment]
We need to update readme to reflect the changes, or preferably go back to a simpler build system without autoconf
