### ISSUE TITLE
makes different udev rules than indicated in the readme

### ISSUE THREAD

**Issue by whoisYoges** [haikarainen/light#132]
I installed [light](https://archlinux.org/packages/community/x86_64/light/) in arch linux from official repo; and it created `90-light-backlight.rules` in `/usr/lib/udev/rules.d/` rather than `90-backlight.rules`, which didn't work and I had to manually rename it to make it work.
Also I had to manually add my user to `video` group. Make it auto detecting if current user is in video group else automatically add current user to the group while installing the package.

**Comment by loong-C** [comment]
可以截图看看吗？正常应该不会出现重名rules文件
![image](https://user-images.githubusercontent.com/47093973/177497528-1cf536a6-bd4c-4c71-8327-9b79c66ae3b0.png)
例如这个，虽然有很多90-*.rules文件，但是并没有重复
