### ISSUE TITLE
Brightness control for secondary screen

### ISSUE THREAD

**Issue by c4traz** [haikarainen/light#14]
From what I see Light does not support setting brightness on a secondary monitor. I run a laptop with a HDMI monitor plugged into it, like many other users too. It would be great if I could adjust brightness to both via Light. But I assume due to the lack of tools out there to do it it may not be trivial?

PS: Light works for me great under Lubuntu+i3wm where all other tools failed me.

**Comment by haikarainen** [comment]
`light` uses `sysfs` for controlling backlight, and any secondary backlight controller should list itself using `light -L`. You may then specify which controller (which monitor) using `light -s <controller>`.

Note however that the brightness levels `light` controls is for backlight brightness (in other words, actual physical brightness). If you want to change brightness settings of monitors via gamma or the likes, you would need to use `xrandr` or something, but this is really only software brightness. I have never come accross  a hardware backlight controller for anything other than internal laptop/PDA monitors in my life.

Please reply if you think I've misunderstood anything, I'll leave this open until we have come to the bottom of this issue.

Thank you for contributing! :+1:

**Comment by c4traz** [comment]
Ah I see, you can disregard this feature request then. Now I understand how different it actually is (software vs. hardware brightness control).

I can achieve lower software brightness on my HDMI with 

`xrandr --output HDMI1 --brightness 0.2`

But it switches back to full brightness seconds after for whatever reason, well that's unrelated to Light. :)

Thank you very much for your time!

**Comment by haikarainen** [comment]
Thanks for the quick response! :+1: 

Just wanted to say that it's probably a daemon that maintains its own brightness stuff. Might also be a driver. Check your desktop environment (KDE, cinnamon, mate, gnome etc). They all probably have different ways of changing brightness.
