### ISSUE TITLE
restore brightness on boot

### ISSUE THREAD

**Issue by ChingChang9** [haikarainen/light#145]
The README says
> Extra features, like setting a minimum brightness value for controllers, or saving/restoring the value for poweroffs/boots.

But my laptop starts at maximum brightness every time I reboot. Are there extra configurations I need to do to get this to save and restore the brightness? I tried using `light -O` before shutdown and checked that it correctly wrote to `~/.config/light/targets/sysfs/backlight/auto/save`, but it was still at maximum brightness after I logged in.

I've also checked that I have `/usr/lib/udev/rules.d/90-backlight.rules` and my user is in the `video` group.

I'm running Alpine Linux on Macbook Air (Early 2015).

**Comment by haikarainen** [comment]
You need `light -I` (capital i) on boot.
