### ISSUE TITLE
how can i integrate with xfce4

### ISSUE THREAD

**Issue by rhoit** [haikarainen/light#15]
recently intel driver has has gotten worst which resulted in tearing with compiz was fixed with the **xf86-video-modesetting** compiz-reloaded/compiz#33

light works perfectly but relies on the command line the, which can be manually binded to keyboard but it does'nt gives the integrated experience like showing the notification.

![screenshot76](https://cloud.githubusercontent.com/assets/1684754/17649804/c65ac9b4-625c-11e6-8d20-3dd55f6ee0d2.png)

or the **Power Manager Plugin** for xfce4

![screenshot77](https://cloud.githubusercontent.com/assets/1684754/17649817/21563038-625d-11e6-9270-459fc917ad7e.png)

Reference:

 - https://www.dinohensen.nl/linux/modesetting-instead-xf86-video-intel-driver-plus-benchmark/#comment-5358

**Comment by haikarainen** [comment]
I think this is an issue you have to take up with the xfce devs

**Comment by rhoit** [comment]
@haikarainen i have been looking at it hours now.. seem something to do with https://git.xfce.org/xfce/xfce4-power-manager/tree/src/xfpm-backlight.c

**Comment by haikarainen** [comment]
Yes, that app is controlling backlight on its own as well as displaying it to the user. Completely separate from this project, so I am closing this!

Good luck!
