### ISSUE TITLE
decrease backlight with respect to minimum value

### ISSUE THREAD

**Issue by abonec** [haikarainen/light#23]
Is it possible to decrease backlight like `light -U 5` but not below minimum? I bind `light` to media keys but it is uncomfortable to decrease backlight and at the and have no light at all. Some parts of documentation is unclear for me.

**Comment by haikarainen** [comment]
You can set a minimum cap value for this very purpose! 

`light -Spc 5`

to set it to never go below 5%.

**Comment by haikarainen** [comment]
What parts of the docs are unclear? So I can work on improving them.

**Comment by abonec** [comment]
```light -Spc 5``` does nothing in verbose mode there is output:
```
Automatic mode -- finding best controller.
/etc/light/mincap/intel_backlight.
error: "could not open file for reading", in "src/helpers.c" on line 68.
error: "could not read value from brightness file", in "src/light.c" on line 581.
intel_backlight.
warning: "could not read controllers brightness file, so controller is not accessible", in "src/light.c" on line 657.
warning: "controller not accessible", in "src/light.c" on line 753.
error: "could not find an accessible controller", in "src/light.c" on line 762.
error: "could not find suitable controller", in "src/light.c" on line 272.
error: "Initialization failed", in "src/main.c" on line 13.
```
After that `light -U 5` will turn off backlight after minimum level.

Not clear parts of readme:
1. Meaning save and restore terms. Will it save between reboots or no.
2. I completely do not understand `Target` section. 

I think all explanations in the readme should be concluded with examples to better understaning of this conceptions. I used to `xbacklight` to inc and dec backlight in `i3wm` but suddenly it was broken. What I need from this kind of program - increase by step (from multimedia key) and decrease (with respect to minimum level, so it never should turn it off). I don't know what also your `light` can do and can't understand other conceptions without examples.

**Comment by haikarainen** [comment]
How did you install light? Run:

**Comment by abonec** [comment]
`make && sudo make install`

**Comment by haikarainen** [comment]
See my updated comment.

**Comment by haikarainen** [comment]
Actually, try to run light as superuser altogether, and read the README.md file for options to set it up without superuser.

**Comment by abonec** [comment]
`/etc/light/mincap` already was here and nothing changed yet. 20 also don't work without `sudo` or with.

**Comment by haikarainen** [comment]
Run these and give me output:

```
light -A 5 -v 3
light -Spc 5 -v 3
```

And please give me the output of 

```
ls -lhsa /sys/class/backlight/
```

**Comment by haikarainen** [comment]
Btw, *Target* is the actual file that will be read/written to by the program. It defaults to the brightness of the controller. But it can be the minimum cap, or for read operations it could also be the maximum brightness of a controller (in raw value). 

The saving/restoring is saved to a file, and can be retreived after boot.

**Comment by abonec** [comment]
```
light -A 5 -v 3
Automatic mode -- finding best controller.
/sys/class/backlight/intel_backlight/brightness.
/sys/class/backlight/intel_backlight/brightness.
/sys/class/backlight/intel_backlight/brightness.
```
```
light -Spc 5 -v 3
Automatic mode -- finding best controller.
/etc/light/mincap/intel_backlight.
error: "could not open file for reading", in "src/helpers.c" on line 68.
error: "could not read value from brightness file", in "src/light.c" on line 581.
intel_backlight.
warning: "could not read controllers brightness file, so controller is not accessible", in "src/light.c" on line 657.
warning: "controller not accessible", in "src/light.c" on line 753.
error: "could not find an accessible controller", in "src/light.c" on line 762.
error: "could not find suitable controller", in "src/light.c" on line 272.
error: "Initialization failed", in "src/main.c" on line 13.
```
```
ls -lhsa /sys/class/backlight/
total 0
0 drwxr-xr-x  2 root root 0 сен 21 11:04 .
0 drwxr-xr-x 68 root root 0 сен 17 20:50 ..
0 lrwxrwxrwx  1 root root 0 сен 17 20:50 intel_backlight -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-1/intel_backlight
```

**Comment by haikarainen** [comment]
The issue is that the program cant access the correct controller files. It's either caused by permission issues or by filesystem changes.

**Comment by risingjason** [comment]
I am having the same issue as well. How would you suggest I fix this?

**Comment by haikarainen** [comment]
Looks like it has suddenly become a common issue. Probably due to changes to syfs or something. I dont have a machine to test it out on sadly, but if anyone have C knowledge, i would suspect it would be pretty easy to fix.

**Comment by haikarainen** [comment]
@risingjason @abonec  please check if Abdullah's pull request fixes your issues! :)

**Comment by haikarainen** [comment]
I'm setting this as closed "for tracking purposes", feel free to reopen if you still get it with the new PQ (I think I might merge it very soon)
