### ISSUE TITLE
setting controller and setting minimum value

### ISSUE THREAD

**Issue by jshamg** [haikarainen/light#24]
i can't set the right controller (acpi_video0 , xcfe4-power-manager sets his value there) and I'm also not able to set the minimum value for the other controller (can't test the other one but at value 0 is the brighness the same as at around 10 on the other controller (radeon_bl0) so i think it was set somewhere else... 
`ls -lash /sys/class/backlight/   
                                                                                                                       
total 0

0 drwxr-xr-x  2 root root 0 Okt 10 00:34 .

0 drwxr-xr-x 61 root root 0 Okt 10 00:34 ..

0 lrwxrwxrwx  1 root root 0 Okt 10 00:35 acpi_video0 -> ../../devices/pci0000:00/0000:00:01.0

/0000:01:05.0/backlight/acpi_video0

0 lrwxrwxrwx  1 root root 0 Okt 10 00:35 radeon_bl0 -> ../../devices/pci0000:00/0000:00:01.0

/0000:01:05.0/drm/card0/card0-LVDS-1/radeon_bl0`

`light -s acpi_video0 -v 3

/sys/class/backlight/acpi_video0/brightness.

/sys/class/backlight/acpi_video0/brightness.

22.22```

`light -A 5 -v 3

Automatic mode -- finding best controller.

/sys/class/backlight/radeon_bl0/brightness.

/sys/class/backlight/acpi_video0/brightness.

ignoring controller as better one already found.

/sys/class/backlight/radeon_bl0/brightness.

/sys/class/backlight/radeon_bl0/brightness.`

**Comment by haikarainen** [comment]
You are using automatic controller mode. Read README to figure out how to specify which controller to use.

**Comment by jshamg** [comment]
`light -s acpi_video0` I already wrote that??? I CANT SET THE CONTROLLER... it stays always in automatic mode

**Comment by haikarainen** [comment]
Sorry, you need to **always** include `-s acpi_video0` in the commandline for every command. The selected controller isn't saved anywhere.  If you do not specify using `-s` every time, it will always default to automatic mode.
