### ISSUE TITLE
[nevermind]

### ISSUE THREAD

**Issue by wilderjds** [haikarainen/light#26]
After my latest mesa upgrade, light consistently fails; here is the output of `light -v3 -s10`

```
error: "could not open file for reading", in "src/helpers.c" on line 68.
error: "could not read value from brightness file", in "src/light.c" on line 565.
warning: "could not read controllers brightness file, so controller is not accessible", in "src/light.c" on line 630.
error: "selected controller is not valid, make sure this application is run as root.", in "src/light.c" on line 275.
error: "Initialization failed", in "src/main.c" on line 13.
```

**Comment by haikarainen** [comment]
Please dont nevermind an issue like this. It's much better to edit your issue with an explanation for future users than to just remove it.

**Comment by haikarainen** [comment]
How did you resolve it?

**Comment by wilderjds** [comment]
I was using -s 10 rather than -S 10 for some reason. Nothing to do with Mesa. Just lack of sleep. 

On November 23, 2017 2:40:38 AM EST, Fredrik Svantesson <notifications@github.com> wrote:
>How did you resolve it?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/haikarainen/light/issues/26#issuecomment-346547923

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
