### ISSUE TITLE
Installation: List dependencies in README, make sure correct permissions are set for man file, don't delete /etc/light

### ISSUE THREAD

**Issue by codethief** [haikarainen/light#27]
First of all, thanks for developing light! It works like a charm!

I wanted to address a few minor points that surprised me during manual installation:

1. `help2man` is nowhere listed as a dependency in the README file.
2. `make install` (or rather `sudo make install`) should make sure that `/usr/share/man/man1/light.1.gz` is world-readable after creating the file. (I set a rather restrictive `umask` for my personal user account and it seems `help2man` is respecting this umask setting when creating `light.1.gz`.)
3. A quick look at the Makefile told me that `make uninstall` will remove the directory `/etc/light` even though this directory is never being created by `make install` in the first place. I suppose this line is legacy code from an earlier version?

**Comment by abdullahibnnadjo** [comment]
Hi, 1. and 2. should be ok with #28.
The `/etc/light` folder is generated by `light` when using the `-c` flag for saving the minimum brightness wanted

**Comment by troglobit** [comment]
Fixed in #28, and then updated again with #42 ... closing issue.
