### ISSUE TITLE
Light stopped working on imac

### ISSUE THREAD

**Issue by ghost** [haikarainen/light#31]
I have an iMac 27`
After I updated my system this working, `light` stopped working. I have to manually edit my `/sys/class/backlight/acpi_video0/brightness` file to get the brigthness changed.

I'm running `light-git` and i'm on `4.15.2-2-ARCH`

**Comment by jgawlik83** [comment]
can confirm the same issue on Solus. Light now requires root to be able to write to `/sys/class/backlight` folder although it was working on Arch for me

**Comment by dmacrae99** [comment]
Do you have the /etc/udev/rules.d/90-backlight.rules? if not make a file with the text below in it and add your user to the video group. Also reboot for the changes to take effect.

ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

**Comment by haikarainen** [comment]
Why you would  _ever_ use 'light' on an Apple product is way beyond my understanding, however, I hope you get it working.

**Comment by troglobit** [comment]
Hi, new co-maintainer here.  Not sure we need to keep this issue open, one solution has been posted (udev rules) and the other one is to se the SUID root bit on `light`, which is done at `sudo make install`.  

We've got a proposal to add support for Policy Kit, which I've not used myself yet, but we welcome pull requests.

@andyperisho @jgawlik83 please let me know if we can close this, or I'll let this comment time out. Thanks! :)

**Comment by haikarainen** [comment]
Closing. Feel free to open a new issue if you still experience problems!
