### ISSUE TITLE
Allow for smooth transitions, with an optional arg that specifies time in milliseconds

### ISSUE THREAD

**Issue by radrow** [haikarainen/light#33]
I would be really nice if there could be possibility to smoothly inc/dec backlight. Now it looks very sharp :(

**Comment by haikarainen** [comment]
This is a common request. It would require a server process/daemon to function optimally. That would require big changes.

Keeping this open in case.

**Comment by haikarainen** [comment]
When #72 is implemented, work on this can be started, without requiring a daemon.
