### ISSUE TITLE
Release 1.0 not functional on Ubuntu 16.04 but HEAD is

### ISSUE THREAD

**Issue by kgilmer** [haikarainen/light#36]
1. Download 1.0 release, compile
2. run light
Expected result: see some value for current backlight
Actual result: no output of command  (other aspects of command don't seem to work either)

However, if I download the current sources (MASTER) and perform the above steps the program works as expected.

Can you make a new release so when I package it I can use your version?

**Comment by haikarainen** [comment]
Run light with -v 3 or likewise, and give me the output. Are you sure its not a packaging problem with regards to permissions?

**Comment by kgilmer** [comment]
light compiled from Release-1.0:

```
$ ./light -v 3
error: "/etc/light does not exist and could not be created", in "src/light.c" on line 244.
error: "Initialization failed", in "src/main.c" on line 13.
```

light compiled from MASTER/HEAD:

```
$ ./light -v 3
notice: "Automatic mode -- finding best controller", in "src/light.c" on line 329.
notice: "found 'intel_backlight' controller", in "src/light.c" on line 885.
warning: "could not open '/etc/light/mincap/intel_backlight' for reading", in "src/helpers.c" on line 203.
warning: "check if this file exists or if you have the right permissions", in "src/helpers.c" on line 203.
notice: "cap file doesn't exist or can't read from it, so assuming a minimum brightness of 0", in "src/light.c" on line 943.
notice: "executing light on 'intel_backlight' controller", in "src/light.c" on line 439.
81.81
```

I'm not certain of anything ( :) ) but do not see this as likely being a packaging issue because I can reproduce the issue by just compiling and running the two variants.

TIA
ken

**Comment by haikarainen** [comment]
This is a packaging error

Create the /etc/light directory upon install

**Comment by haikarainen** [comment]
possibly /etc/light/mincap as well

**Comment by haikarainen** [comment]
https://github.com/haikarainen/light/releases/tag/1.1

**Comment by kgilmer** [comment]
Thanks for your attention and time!
