### ISSUE TITLE
This project is looking for a maintainer

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/light#37]
As the title states.  This project seems to be growing in popularity still to this date, something that I never expected. The problem is that I no longer have time to maintain it (with 3 kids and a fulltime job).

Requirements:

 * Ability to get the job done

Feel free to reply here or contact me at fredrik _dot_ haikarainen _at_ google mail

**Comment by CameronNemo** [comment]
I would be willing to help. Is there something in particular you want help with?

**Comment by CameronNemo** [comment]
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by haikarainen** [comment]
@CameronNemo Fixing issues, both old ones and new ones that come up. Cleaning up the codebase, adding new features if they are heavily requested, general mainenance.

Create some pull requests if you feel like it, it would be very appreciated. If we get something great going I'll just give you write permissions on the repo once trust is established.

I will not be transferring the repo 😅

**Comment by CameronNemo** [comment]
>I will not be transferring the repo

You could do it to an organization that you are a sole admin of, then give others write access.

The only reason I put the link there is because you asked in another issue if you could "orphan a github project".

**Comment by CameronNemo** [comment]
Off the top of my head, some things that could help the project (in no particular order):

* refactoring the `light/light.c` file, which clocks in at 887 lines of C
* adding optional PolicyKit integration so that unpriveleged users who are physically present at the machine can use the tool -- no suid necessary
* adding optional Linux Security Module confinement using AppArmor, so the tool is restricted to accessing a subset of what it could access with standard user/group/acl permissions
* renaming! light is a very generic name and I feel like it could be more descriptive and/or searchable
* distributor outreach! without packagers for Fedora, Arch, Debian, etc the tool would not reach nearly as many hands with such ease

**Comment by haikarainen** [comment]
1. Instead of doing big refactors, I would  just rewrite it in modern C++ instead. Writing it in C was mostly educational when I first ported it from bash, also C++ would kill tons of clutter.
2. Sounds cool
3. Sounds cool
4. Heard this argument before. Its actually very easy to find on google if you add contextual clues. `light backlight linux` brings the repo up as first result for me, for example. I'm against a namechange.
5. Yes! Ive been down this path before. I used to maintain an aur PKGBUILD and a deb package for Debian/Ubuntu, but its a ton of work (.debs at least). Feel free to do it if you wish.

**Comment by CameronNemo** [comment]
I understand that you do not want large, hard to review refactors. I was mainly interested in splitting the argument parsing and `handleInfo` functions from the execution functions. This could quickly and simply shave ~300 lines from the operation execution logic (that's more than a third of the file length).

**Comment by CameronNemo** [comment]
Also I cannot port this codebase to C++, as I lack the experience or willingness to learn C++. I do have experience with Vala, however. The language has a rich object model, C-style imperative programming, with a few javascript features thrown in (anonymous functions, for example). It actually compiles to native C code, though it depends on glib.

**Comment by troglobit** [comment]
Just a few comments:

- Thanks for a great little tool in the true UNIX spirit, really saved my bacon today! :-)
- I could help merge/review pull requests. I've worked on [libConfuse](https://github.com/martinh/libConfuse/) in a similar manner.
- PolicyKit support sounds neat
- An AppArmor profile would also be great
- Dunno about Vala, that would require having the runtime installed and from what I can understand the point of the project is for use with minimal installations/window managers

My vote would be to not change anything, both the name and the fact there are no external deps is awesome \o/

**Comment by haikarainen** [comment]
Thanks for your input @troglobit, very appreciated! Feel free to contribute to the repo as you see fit, let me know if you need any permissions to the repo.

**Comment by troglobit** [comment]
@haikarainen OK, I can whip a couple of pull requests tomorrow. If you like 'em we can talk repo rights ;-)

**Comment by troglobit** [comment]
@haikarainen I've pushed two PR's now, to indicate the direction in which I'd like to take the project, with your blessing of course.  If you approve, you can add me as a collaborator.  The first order of business will be to merge the outstanding PRs: #28 and #30, and then move on to plan v1.2

**Comment by haikarainen** [comment]
@troglobit invited you as collaborator on the repo, go crazy! :)

**Comment by troglobit** [comment]
@haikarainen Cool, thanks man, I'll do my best! :+1:
