### ISSUE TITLE
Add support for --with-udev to configure script to avoid SUID root

### ISSUE THREAD

**Issue by troglobit** [haikarainen/light#45]
SUID root binaries after install is usually frowned upon.  With light we have the option to instead use the udev rules, and as long as the user is member of the `video` group light would operate the same as with SUID root set.

**Comment by CameronNemo** [comment]
You'll need to use a different storage dir per user otherwise the saved brightness and minimum cap files will conflict.

**Comment by CameronNemo** [comment]
If you are root (through setuid or polkit) you can write to /var/cache easy and overwrite old values too. But if you are an unprivileged user you may not be able to overwrite values set by another user. Even if the video group has access to /var/cache/light.

**Comment by CameronNemo** [comment]
It's much cleaner to do it by user when you are unprivileged.

**Comment by troglobit** [comment]
Thank you for explaining, I didn't consider that.

To me that sounds like we should move away from a global directory altogether and use `~/.cache/light/` instead.
