### ISSUE TITLE
Can't increase brightness on ATI propietary driver

### ISSUE THREAD

**Issue by AnderRasoVazquez** [haikarainen/light#5]
I've installed ATI propietary drivers on Arch Linux and now I can't raise brigtness. At least I can decrease it or set it.

Keep up the good  work!

**Comment by haikarainen** [comment]
Sounds very weird, sorry for the late reply btw.

What controllers do you have available in `/sys/class/backlight` ?
```bash
ls /sys/class/backlight
```

And what happens if you try to read the brightness and max brightness respectively of the available controllers?
```bash
ls /sys/class/backlight/<controllername>/brightness
ls /sys/class/backlight/<controllername>/max_brightness
```

Thanks a ton for reporting the issue!

**Comment by AnderRasoVazquez** [comment]
**It founds two folders:**
`$ ls /sys/class/backlight`
`acpi_video0  acpi_video1`

#### File's values and behavior

**/sys/class/backlight/acpi_video0/max_brightness** -> 7
**/sys/class/backlight/acpi_video1/max_brightness** -> 7

**/sys/class/backlight/acpi_video0/brightness**
It varies from 0 to 7 when I change brightness with Light
Brightness only increases if `light -A >=15` if I try smaller values it doesn't increase.
But if I try `light -U 1` brightness decreases a value from 7 to 0. It means that I can decrease brightness seven times.

**/sys/class/backlight/acpi_video1/brightness**
Always 7, doesn't change with `light`, but if I change it manually (0 to 7) with "sudo nano" brightness changes. After that, If I change the value with `light`, it will read `/sys/class/backlight/acpi_video0/brightness` value and change brightness acording to it.
For example:
I change manually `acpi_video1` to 7 which increases backlight to the maximum value, but `if acpi_video0 = 5` (for exampe) when I do `light -U 1` `acp_video1` remains at 7 and `acpi_video0` decreases to 4, decreasing brightness to 4 (3 leves instead of 1)

This is really extrange behavior, when I used open source radeon drivers I had lots of levels (255) and Light worked perfectly. I hope this helps =)

**Comment by haikarainen** [comment]
I think I know what the problem is, I dont quite have time to fix it atm. but what should work for you is if you try to add like this instead (using raw values):

```
light -Ar 1
```

Note the -r flag, this means light will work using raw controller values instead of percentage values. I will get on this as soon as I have time!

**Comment by AnderRasoVazquez** [comment]
Yes, it worked. Thanks for your time ^^

**Comment by haikarainen** [comment]
@AnderRasoVazquez I have submitted a patch for what I think will fix your problem, it would be highly appreciated if you take a look at it and verify when you have time.
