### ISSUE TITLE
Cannot upgrade light

### ISSUE THREAD

**Issue by micrus** [haikarainen/light#55]
From the last update I'm no more able tu update light. When I run yay it end with error:
`errore: impossibile eseguire l'operazione richiesta (file in conflitto)
light-git: /usr/local/share/man exists in filesystem (owned by filesystem)
`

**Comment by haikarainen** [comment]
I am guessing you are running Arch Linux and the light-git AUR?

**Comment by haikarainen** [comment]
If I'm correct, try removing light completely, and reinstall from the newest PKGBUILD on AUR

**Comment by micrus** [comment]
True, running archlinux with AUR's light-git.

Unfortunely tried but does not work

**Comment by haikarainen** [comment]
Allright, please post full output.

It does sound like you need to specify the prefix for configure to make it install into the right directory (and not in usr/local).  In other words `./configure --prefix=/usr` instead of `./configure`´

Additionally, I dont think help2man is a required dependency anymore.

**Comment by haikarainen** [comment]
Ah yes, I know some of these words. Did you try patching the PKGBUILD as suggested? Should be pretty straightforward, makepkg -si IIRC

**Comment by micrus** [comment]
Sorry for ignorance, where should be located the PKGBUILD?

**Comment by haikarainen** [comment]
Did you patch the PKGBUILD to output to /usr instead of /usr/local?  

Tomorrow I will get some new hardware, which means I can afford to put Linux on my old trusted laptop and fix this issue.

**Comment by troglobit** [comment]
Thank you @haikarainen for stepping in, I'm quite out of my depth when it comes to Arch ... tried installing it but it's quite different (!) from environments I'm used to.

**Comment by haikarainen** [comment]
I have submitted a PKGBUILD in the repo instead. Clone the repository, then do:

* `cd archlinux`
* `makepkg -s`
* `sudo pacman -U <generated-package>`

replace <generated-package> with the actual generated package  (for example `ight-1.1.2.r64.gc889827-1-x86_64.pkg.tar.xz`)
