### ISSUE TITLE
Test support for the openrazer driver

### ISSUE THREAD

**Issue by WhyNotHugo** [haikarainen/light#57]
My keyboard's driver exposes the backlight brightness via the `/sys/bus/hid/drivers/razerkbd/0003:1532:0232.0003/matrix_brightness` file, with values between 0 and 255.

Is it somehow possible to make `light` pick this up, so I can use it to manage my keyboard's backlight?

**Comment by CameronNemo** [comment]
light's architecture doesn't really look for files at that path or with that name. Are you using the https://github.com/openrazer/openrazer driver? Maybe you can use their tooling.

**Comment by WhyNotHugo** [comment]
Yes, I'm using openrazer. Most of the tools around it are GUIs, but I'm actually looking at something to run programatically when I press the brightness keys on my keyboard (via sxhkd, or i3wm).other 

I already use `light` on my PC, as well as for the display backlight, that's why this was my first instinct. If it's too complex for `light`, I might just create a python script around openrazer.

**Comment by haikarainen** [comment]
Since we already have support for keyboard leds, I think it might be neat to look into the possibilities to support razer/steelseries leds too. As long as we can do it while respecting the GPL license, and also without any third party deps or unnecessary crud.

**Comment by haikarainen** [comment]
I think it might be a good time to look at abstracting the different device interfaces a bit. This is where I think that a C++ rewrite would shine (with its inheritance, interfaces and whatnot), however it should be totally doable with C as well.

Where can I read more about this brillo thing you're talking about? Couldn't find any repos or likewise..

Anyway, if we could create an interface system that allows us to have different device implementations (for different kind of LEDs basically), then it would make it much easier to add more devices later on. Right now it's kind of hardcoded with how we select backlight/keyboard device. I would be totally okay if we allow _optional_ dependencies to add more interfaces, maybe even through a module/plugin system. Not sure how far we should take this?

**Comment by troglobit** [comment]
I'm not really comfortable with C++ myself, and I think we could just start out by factoring out paths to `/sys/class/leds`, in this case, add possibility to use a custom path for a controller ... and move on from there. 

It's at GitLab https://gitlab.com/cameronnemo/brillo/

**Comment by haikarainen** [comment]
Ah neat. Didnt know we had a fork :) 

I think some sort of device interface can be a big pro here though.  Some sort of neat API to abstract away implementation details, and simply let "users" of the API enumerate devices, their names, maybe a device type (sysfs, custom or likewise), and to call functions like `set_brightness`/`get_brightness`/`get_max_brightness` etc. I'm not fully experienced with the best approach here with C, however structs with function pointers to implementations could be one way to go. 

What do you think @troglobit? You seem to have become the primary maintainer of this repo lately so I definitely think your input is valuable here.

**Comment by haikarainen** [comment]
To add a little to that, the benefits would obviously be that some implementations (like in this case) have different ways and also different filenames (matrix_brightness) to control the device.  We could also have a sysfs base-interface ontop of the base-interface to reuse code from within the sysfs domain.

**Comment by haikarainen** [comment]
I would love to take this project upon myself if you think it's too much effort. It shouldn't be more than a weekends worth of work IMO. Then again I'm more used to C++ but I dont think it should be much different. 

You wouldnt need a plugin-system to begin with either, you could start off by simply creating the abstracting API and implementing the sysfs and razer devices on top of that.  Let me see what I could come up with!

**Comment by troglobit** [comment]
@haikarainen Sure, go right ahead! Looking forward to see how this develops :sunglasses::+1:

**Comment by haikarainen** [comment]
@WhyNotHugo I am going to read up on the /sys/bus/hid directories, however I think it may be helpful if I could have the output of `ls -lhsa /sys/bus/hid/drivers/razerkbd/0003:1532:0232.0003/` as well as for other related directories until then. It is difficult to write code for a driver/hardware that I do not own :) I also noticed that there exists other brands that follow the same pattern (under sys/bus/hid/drivers), for example Asus.  Seems like this addition to the code have the potential to add a _lot_ of new device support, so with that in mind; Very good initiative!

**Comment by haikarainen** [comment]
Just a headsup; This will probably become a very large commit, good thing that the project is small!

**Comment by WhyNotHugo** [comment]
@haikarainen Yup, here you go, thanks!

```
$ ls  -lhsa /sys/bus/hid/drivers/razerkbd/0003:1532:0232.0003/  
total 0
0 drwxr-xr-x 5 root plugdev    0 Aug 25 03:14 ./
0 drwxr-xr-x 5 root root       0 Aug 25 03:14 ../
0 -r--r--r-- 1 root plugdev 4.0K Aug 25 03:14 country
0 -rw-rw---- 1 root plugdev 4.0K Aug 25 03:14 device_mode
0 -r--r----- 1 root plugdev 4.0K Aug 25 03:14 device_serial
0 -r--r----- 1 root plugdev 4.0K Aug 25 03:14 device_type
0 lrwxrwxrwx 1 root plugdev    0 Aug 25 03:14 driver -> ../../../../../../../bus/hid/drivers/razerkbd/
0 -r--r----- 1 root plugdev 4.0K Aug 25 03:14 firmware_version
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 fn_toggle
0 drwxr-xr-x 3 root plugdev    0 Aug 25 03:14 hidraw/
0 drwxr-xr-x 3 root plugdev    0 Aug 25 03:14 input/
0 -r--r----- 1 root plugdev 4.0K Aug 25 03:14 kbd_layout
0 -rw-rw---- 1 root plugdev 4.0K Aug 25 03:14 logo_led_state
0 -rw-rw---- 1 root plugdev 4.0K Aug 25 03:14 matrix_brightness
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 matrix_custom_frame
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 matrix_effect_breath
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 matrix_effect_custom
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 matrix_effect_none
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 matrix_effect_reactive
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 matrix_effect_spectrum
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 matrix_effect_static
0 --w--w---- 1 root plugdev 4.0K Aug 25 03:14 matrix_effect_wave
0 -r--r--r-- 1 root plugdev 4.0K Aug 25 03:14 modalias
0 drwxr-xr-x 2 root plugdev    0 Aug 25 03:14 power/
0 -r--r--r-- 1 root plugdev 4.0K Aug 25 03:14 report_descriptor
0 lrwxrwxrwx 1 root plugdev    0 Aug 25 03:14 subsystem -> ../../../../../../../bus/hid/
0 -rw-rw---- 1 root plugdev 4.0K Aug 25 03:14 test
0 -rw-r--r-- 1 root plugdev 4.0K Aug 25 03:14 uevent
0 -r--r----- 1 root plugdev 4.0K Aug 25 03:14 version
```

There seems to be nothing indicating the maximum brightness -- it's simply always 255.

I'm not sure what else might help, but do let me know. I think that  structs with functions pointers are probably the cleanest way to go in plain C. :)

**Comment by haikarainen** [comment]
@WhyNotHugo Thank you, very helpful!  I found some very useful docs on https://github.com/openrazer/openrazer/wiki/Using-the-keyboard-driver as well! 

Aiming for as much functionality as possible here (like setting colors for individual keys) but I cant promise anything!

**Comment by WhyNotHugo** [comment]
I think tweaking individual keys is kinda out-of-scope for what `light` does (both in term of complexity, and, personally, it's really way outside by usage scenarios).

**Comment by haikarainen** [comment]
The new codebase makes it so easy that it would be a shame not to implement it. Light was created with monitor backlights in mind, but has since come to support leds in different forms as well. Why not individual leds on custom keyboards too, if the hardware supports it?

**Comment by haikarainen** [comment]
Just a notice; I finally got around to install Linux on my "old" T460 so I will create a PR for this this weekend.

**Comment by haikarainen** [comment]
changed has been merged to allow implementation of this. Feel free to grab it if you have razer hardware! Read DOCUMENTATION.md for required steps to implement an enumerator

**Comment by haikarainen** [comment]
Starting implementation of this now. I cant test it myself though, so I'm counting on you to be QA on this @WhyNotHugo

**Comment by haikarainen** [comment]
Closing because of low interest
