### ISSUE TITLE
Light won't build with GCC <= 4.7

### ISSUE THREAD

**Issue by NorthSailor** [haikarainen/light#64]
After the change in `src/Makefile.am` (changing `-std=gnu99` to `-std=gnu18`) light won't build without the very latest version GCC.

Not sure if this is exactly an issue but the latest packaged version for Ubuntu 18.04 is 4.7 and I'm not sure how many people would be willing to build GCC from sources.

**Comment by haikarainen** [comment]
Thats very unimpressive of Ubuntu. 4.7 was released in 2012, which is 6 years ago (!!). The current stable release is 8.2.

I'll fix it right away

**Comment by troglobit** [comment]
What, that is not correct at all?! The gcc version in Ubuntu 18.04 is 7.3.

https://packages.ubuntu.com/bionic/gcc

**Comment by troglobit** [comment]
-std=gnu11 would work, both with GCC 7.3 ... and even down to GCC 4.7, which was in Ubuntu 12.10.

**Comment by NorthSailor** [comment]
@troglobit Oops, indeed my fault I saw the wrong version number. But still, the issue remains.
