### ISSUE TITLE
no any device support on HP-Z420 with Ubuntu-14.04.5 64bit OS?

### ISSUE THREAD

**Issue by zhengfish** [haikarainen/light#65]
root@z420 ~/light-master/src # ./light -L
couldn't find a device target at the path "sysfs/backlight/auto". Use -L to find one.

root@z420 ~/light-master/src # ./light -G
couldn't find a device target at the path "sysfs/backlight/auto". Use -L to find one.

**Comment by haikarainen** [comment]
Please post output of `ls -lhs /sys/class/backlight`

Also please try to run it with root.

**Comment by haikarainen** [comment]
Hmm actually, theres a bigger issue with this. Right now we kinda assume that you have to have at least one backlight controller to be able to use light. Will fix right now

**Comment by haikarainen** [comment]
@zhengfish I have resolved the issue, probably.  Please test and make sure.

**Comment by zhengfish** [comment]
Hello, @haikarainen, 
Sounds it still not work.

root@z420 ~/light-master # ls -lhs /sys/class/backlight
total 0
root@z420 ~/light-master # ./src/light -L
No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.

Listing device targets:
        sysfs/leds/input5::numlock
        sysfs/leds/input5::capslock
        sysfs/leds/input5::scrolllock
        util/test/dryrun

**Comment by haikarainen** [comment]
Hey!

It actually does work as advertised. You don't seem to have a backlight driver installed in your system (as it doesnt come up in the sysfs). I see now that you are on a workstation and not a laptop, which would explain this.

External monitors rarely provide functionality like controlling the backlight, and when they do, you need a monitor-specific driver to control it. And if this driver does not expose it via the standard sysfs backlight interface, then light will not be able to recognize it with the standard sysfs enumerator. The options here is either to fix the driver, or to implement a custom enumerator for the specific monitor brand.

Hope this answers your questions, you can still control your keyboard LEDs using light, by specifying their respective targets using the -s switch. Example:

```
light -s sysfs/leds/input5::capslock -S 100
```

If you want to be able to support your monitor, please specify what model of monitor it is and if it has any USB connectivity, and I'll see what I can do.
