### ISSUE TITLE
Checklist for v1.2 release

### ISSUE THREAD

**Issue by troglobit** [haikarainen/light#67]
- [x] Update man page, issue #66 
- [x] Update Debian/Ubuntu packaging, i.e. add entry to debian/changelog, issue #68

Add more items in comments and we'll update the checklist.

**Comment by troglobit** [comment]
I've added #57 to the v1.2 milestone, but not to the checklist. I guess we'll release v1.2 even if we've not yet received any feedback.

**Comment by troglobit** [comment]
So, we're done.

@haikarainen Should we wait some more for input on #57 or just do the v1.2 release?

**Comment by haikarainen** [comment]
Great work man, very appreciated! <3 

I'd be very happy to put this release out. And sure, no reason to have that branch around.

**Comment by troglobit** [comment]
OK, then I'll clean up that branch and prepare for a release sometime tomorrow.

**Comment by troglobit** [comment]
Allow me to announce the release of [v1.2](https://github.com/haikarainen/light/releases/tag/v1.2), fresh from the oven! :-)
