### ISSUE TITLE
AUR4

### ISSUE THREAD

**Issue by Enzime** [haikarainen/light#7]
The Arch User Repository is updating to a new version tomorrow, and while light-git is unadopted, it won't show up in searches. So, I'm assuming you'll also want to adopt this, if not I'm willing to.

https://aur4.archlinux.org/packages/light-git

**Comment by haikarainen** [comment]
Hey Enzime!

If you would be interested in adopting the AUR package that would help me (and anyone who uses it) out a lot! Please tell me if you need anything from me in order to achieve this.

**Comment by Enzime** [comment]
The package has already been adopted (but not by me), so it will now show up on the AUR again.
