### ISSUE TITLE
Pluginsystem, split light into library/executable

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/light#73]
Plugins to install new enumerators. Modules will be installed to `/usr/lib/light/enumerators/`, which will be automatically iterated over on program start, loading any modules residing in that directory. Optimally requires light to be split into a library and executable, to let plugins reuse as much code as possible from light.

**Comment by haikarainen** [comment]
Eh, plugins may want/need root privs too. I see the security hole you're pointing out, but a lot of applications already work like this. I do not think that this will be a problem for users in practice. Light can operate without root as well, so that is an option for paranoid people.

**Comment by CameronNemo** [comment]
light doesn't even sanitize its environment. that would be a first step if there is a serious desire to keep the setuid bit around.

**Comment by haikarainen** [comment]
@CameronNemo  Feel free to elaborate

**Comment by CameronNemo** [comment]
http://nob.cs.ucdavis.edu/bishop/secprog/1987-sproglogin.pdf

**Comment by haikarainen** [comment]
@CameronNemo I might get buried in that kinda stuff if I ever find time. Right now it's not really a priority (for me). 

Until then, feel free to open an issue on the matter and maybe even make a pull request (IIRC you even have a fork, lifting those fixes into this project may also be beneficial of course.)

**Comment by CameronNemo** [comment]
my fork (`brillo`) doesn't have a setuid option, it uses policykit for privilege escalation. `pkexec` does all the environment sanitation before it is ever executed.
