### ISSUE TITLE
Checklist for 1.3 release

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/light#74]
- [ ] Implementing #72 

- [ ] Implementing #33
 
- [ ]  Implementing #73 

- [ ] Separating razer into its own plugin

**Comment by haikarainen** [comment]
Please push your changes on branch 1.3-dev, we will create PR when its time for merge

**Comment by AloisMahdal** [comment]
Just curious: are you intentionally not using milestones feature? :-)  (Again, I'm not saying it's better or that I like it, I was just genuinely curious.  Also I know this is OT so feel free to ignore/delete my comment or point me to a discussion forum.)

**Comment by AloisMahdal** [comment]
Well, It does provide one more vendor-lock to GitHub.  And I'm actually one of those who moved their stuff away from github (pagure.io) after "that day", so yeah... I'm fine with light getting less vendor-locked.

**Comment by haikarainen** [comment]
@AloisMahdal I guess you mean the Microsoft-thing? I haven't really noticed any bad moves in practice yet, so fingers crossed..

**Comment by haikarainen** [comment]
I have assigned milestones, so no need for this

**Comment by maximbaz** [comment]
@haikarainen it has been quite some time since the latest release, some useful commits were merged in the meantime [and users ask for them](https://bugs.archlinux.org/task/63629), would you consider cutting off `1.3` (or perhaps `1.2.1` if you consider these changes minor)?

**Comment by maximbaz** [comment]
a friendly ping @haikarainen

**Comment by haikarainen** [comment]
@maximbaz Ill get on this when I find time. Development on this project is kind of slow, as I rarely use Linux myself these days.. A release from current master shouldnt be a major issue though I hope.

@troglobit Do you still have pejl on the deb package?

**Comment by troglobit** [comment]
@haikarainen Yes, I could have a look at it if needed.

**Comment by haikarainen** [comment]
@troglobit  Feel free to create them for https://github.com/haikarainen/light/releases/tag/untagged-38ab8755eed707e2e8c4 when you find time

**Comment by troglobit** [comment]
@haikarainen OK, I'll try to get it done tonight.  Need my Debian machine for that (slightly older libc which increases compat with other distros).

If I forget, please feel free to remind me ... anyone :)

**Comment by haikarainen** [comment]
@troglobit poke

**Comment by troglobit** [comment]
Thanks for the reminder.  Took an early morning to sit down and fix this, but cannot find the tag/hash?

```
jocke@moe:~/Troglobit/light [master]$ git checkout 38ab8755
error: pathspec '38ab8755' did not match any file(s) known to git
```

**Comment by haikarainen** [comment]
Thats weird. The release is a draft and is untagged. Do you have access to edit the draft?

**Comment by troglobit** [comment]
Yeah I can edit the draft, but is says `untagged-38ab8755eed707e2e8c4` in the title, so I assumed that was the commit you wanted the .deb files to be created from?  If you want to do a properly tagged v1.3 release (without the planned features for v1.3), then I can of course do that instead.

**Comment by haikarainen** [comment]
Sorry, I have no idea how any of this works lol. This isn't the 1.3 release. Maybe we should just make it a 1.2.1 tagged release?

**Comment by haikarainen** [comment]
@troglobit plz try now

**Comment by maximbaz** [comment]
Thanks for tagging `1.2.1`, works well for me on Arch, I'll push a new release now 🙂

**Comment by haikarainen** [comment]
@maximbaz that's great. Sorry for the delay.
