### ISSUE TITLE
Debian packaging installs udev rules in `/usr/lib`, but they should be in `/lib`.

### ISSUE THREAD

**Issue by CameronNemo** [haikarainen/light#75]
Please consider adding an option to override the udev rules directory.

See [here](https://github.com/Yubico/yubikey-personalization/blob/master/configure.ac#L150) for an example.

**Comment by troglobit** [comment]
We'll look into it for the next release cycle, thanks!

**Comment by sim590** [comment]
Is there a version where this problem doesn't occur? Because the program cannot be run without sudo otherwise. Thanks.

**Comment by sim590** [comment]
I've made a pull request. I mentionned that it fixes this issue in case that is indeed sufficient. Advise me if it is otherwise.

**Comment by haikarainen** [comment]
Thank you for your contribution @sim590  !

**Comment by sim590** [comment]
All the pleasure is mine! :dancer:
