### ISSUE TITLE
System randomly hangs

### ISSUE THREAD

**Issue by JunnanZ** [haikarainen/light#80]
Device: XPS 13
OS: Arch Linux
Kernel: 4.18.12-arch1-1-ARCH
WM: i3

Sometimes when I adjust the backlight by pressing the buttons (which I map to use `light`), the whole system hangs for a few second. I can't move the mouse and change workspaces, etc. It happens randomly. Below are the relevant logs:

Oct 25 12:15:52 junnan root[11777]: [57B blob data]
Oct 25 12:15:52 junnan root[11779]: BrightnessDown pressed
Oct 25 12:16:01 junnan rtkit-daemon[919]: The canary thread is apparently starving. Taking action.
Oct 25 12:16:01 junnan rtkit-daemon[919]: Demoting known real-time threads.
Oct 25 12:16:01 junnan rtkit-daemon[919]: Successfully demoted thread thread 979 of process 913 (/usr/bin/pulseaudio).
Oct 25 12:16:01 junnan rtkit-daemon[919]: Successfully demoted thread 913 of process 913 (/usr/bin/pulseaudio).
Oct 25 12:16:01 junnan rtkit-daemon[919]: Demoted 2 threads.
Oct 25 12:16:01 junnan root[11785]: [57B blob data]
Oct 25 12:16:01 junnan root[11787]: BrightnessUpButton pressed

I first thought it was because I adjusted the brightness by holding down the button, consecutively calling `light`. But it also happened today when I just press it twice.

By the way, this issue only happens when I use `light`.

**Comment by haikarainen** [comment]
Having a hard time believing that light is the culprit here.

Seems like pulseaudio has two realtime threads that is choking out other processes. Why you only experience it when running light I have no idea. What buttons are mapped to light? Is it possible that they are also mapped to something else?

**Comment by JunnanZ** [comment]
You are right. There is something wrong with my brightness buttons. I just remember this issue had happened before I started using `light`.
