### ISSUE TITLE
light: invalid option -- 'k'

### ISSUE THREAD

**Issue by xQsme** [haikarainen/light#81]
Upgraded packages last night, can't seem to get keyboard backlight value

**Comment by haikarainen** [comment]
Sounds very weird, show me your full commandline and I'll try to repro it

**Comment by haikarainen** [comment]
For reference, the correct syntax is:

    light -s "sysfs/leds/tpacpi::kbd_backlight" -G

`-s` specifices the target to write to, in this case it's set to `sysfs/leds/tpacpi::kbd_backlight`
`-G` specifies that we get the brightness value 


You can also use `-v 3` to get extra debug info

**Comment by haikarainen** [comment]
Nevermind, I just realized you're using the old syntax, type `light -L` to see which targets are available on your system, specify them with `-s`, and then use `-S 100` to set and `-G` to get. Read the readme on the repo for further info!

**Comment by xQsme** [comment]
Ok my bad i'll take a look at the sources, thanks
