### ISSUE TITLE
Not detecting desktop monitors?

### ISSUE THREAD

**Issue by rieje** [haikarainen/light#86]
Sorry if noob question, but `light` is not detecting either of my dual desktop monitors:

    $ light -L

    No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.

    Listing device targets:
	    sysfs/leds/input7::numlock
	    sysfs/leds/input7::capslock
	    sysfs/leds/input7::scrolllock
	    util/test/dryrun

I don't think my monitors are anything special and aren't super new--do external monitors typically not support hardware brightness? I also use redshift that has no problem adjusting brightness, but I prefer to use a dedicated tool for setting brightness. light works out of the box for my laptop.

Just curious. Thanks.

**Comment by haikarainen** [comment]
Backlight adjustment via DVI/HDMI/DP isnt really a thing as far as Im concerned, although some manufacturers have released APIs for their line of monitors to do this. This would require an integration to be created in light, which involves implementing an enumerator etc. for the given API

**Comment by lukelex** [comment]
@rieje look up ddcutil and be happy.

**Comment by haikarainen** [comment]
> @rieje look up ddcutil and be happy.

Damn, we should implement an enumerator on top of that, if it can control desktop displays

**Comment by lukelex** [comment]
Here's a script I use on my Polybar to control my monitor's brightness. Not sure if this will help but it might be a start.
https://github.com/lukelex/dotfiles/blob/master/linux/scripts/brightness

**Comment by haikarainen** [comment]
@lukelex Thanks! Yeah it looks pretty straightforward, I might get on this soon. If you wanna give it a shoot, docs for implementing an enumerator is found here: https://github.com/haikarainen/light/blob/master/DOCUMENTATION.md#implementing-an-enumerator

You also have reference implementations for razer at:
https://github.com/haikarainen/light/blob/master/src/impl/razer.h
https://github.com/haikarainen/light/blob/master/src/impl/razer.c

We want to name the devices/targets after something unique to the system (preferably their i2c device paths), so for example we don't want to use the monitor serial number, as there might be duplicates for multimonitor setups.

**Comment by lukelex** [comment]
I won't have any time soon to dive into this, so feel free to go for it.
