### ISSUE TITLE
Tried to add this suedoers, didn't seem to work

### ISSUE THREAD

**Issue by chrism2671** [haikarainen/light#87]
I am aware of this issue:
https://github.com/haikarainen/light/issues/35

I'm using Ubuntu 18.04, using the packaged deb. Instead of going down the udev route, I've tried to add it to the sudoers list, as follows with `visudo`:

```
#
# This file MUST be edited with the 'visudo' command as root.
#
# Please consider adding local content in /etc/sudoers.d/ instead of
# directly modifying this file.
#
# See the man page for details on how to write a sudoers file.
#
Defaults	env_reset
Defaults	mail_badpass
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

# Host alias specification

# User alias specification

# Cmnd alias specification
Cmnd_Alias PASSWORDLESS = /usr/bin/light

# User privilege specification
root	ALL=(ALL:ALL) ALL

chris   ALL=(ALL) ALL
chris   ALL=(root) NOPASSWD: PASSWORDLESS

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d

```

This *should* work, but it doesn't. Anyone know what I'm missing here?

**Comment by haikarainen** [comment]
Sorry I dont know. It seems like a sudo thing though, and not light-specific. Also I dont have a linux box to try anything either. Keeping it open in case, good luck!

**Comment by troglobit** [comment]
@chrism2671 This is what I found with a quick google https://unix.stackexchange.com/a/248495/163344

**Comment by chrism2671** [comment]
Thank you! I did continue to experiment with this, but in the end I gave up, as I managed to configure xbacklight with xorg.conf, which doesn't require root. Happy to close this issue if you are.

**Comment by troglobit** [comment]
@chrism2671 OK, thank you for getting back to us.  Have a nice day! :)
