### ISSUE TITLE
run light in user mode (i.e., without root permission)?

### ISSUE THREAD

**Issue by bl4ck5un** [haikarainen/light#90]
Hi, thanks for the useful tool. I've been using light for a while with `i3`. I recently upgraded to Ubuntu 19.04 and found out that `light` requires root permission. Could you advise how to use light in user mode?

These might be useful:

~~~
$ cat /usr/lib/udev/rules.d/90-backlight.rules
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="leds", RUN+="/bin/chgrp video /sys/class/leds/%k/brightness"
ACTION=="add", SUBSYSTEM=="leds", RUN+="/bin/chmod g+w /sys/class/leds/%k/brightness"

$ light -A 5 -v3
helpers.c:21: Error: could not open '/home/fanz/.config/light/targets/sysfs/backlight/auto/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
helpers.c:45: Error: could not open '/sys/class/backlight/intel_backlight/brightness' for writing
helpers.c:45: Error: Verify it exists with the right permissions
impl/sysfs.c:133: Error: failed to write to sysfs device
light.c:865: Error: failed to write to target
main.c:20: Error: Execution failed
~~~

**Comment by haikarainen** [comment]
As readme states: make sure that your user is part of the video group, otherwise you will not get access to the devices.

Also verify that Ubuntu 19.04 actually uses `/usr/lib/udev` as the path for udev, or you have to specify while building (checkreadme).

**Comment by haikarainen** [comment]
Also I guess you could try this package instead: https://github.com/haikarainen/light/releases/download/v1.2/light_1.2_amd64.deb

However I dont know how up to date it is

**Comment by troglobit** [comment]
+1 on being part of the video group.  

The latest release of light, including the `.deb` file, support this.

**Comment by bl4ck5un** [comment]
Thanks. I missed the bit about the video group. Now it works.
