### ISSUE TITLE
Light stopped working suddenly

### ISSUE THREAD

**Issue by cubetastic33** [haikarainen/light#92]
I've been using light for months now, and it works really well. But, suddenly, I'm surprised to find that light isn't working. I tried the command `light -S 0` with verbosity 3, and this is the result:
```
$ light -S 0 -v 3
helpers.c:21: Error: could not open '/home/aravk/.config/light/targets/sysfs/backlight/auto/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
helpers.c:45: Error: could not open '/sys/class/backlight/intel_backlight/brightness' for writing
helpers.c:45: Error: Verify it exists with the right permissions
impl/sysfs.c:133: Error: failed to write to sysfs device
light.c:695: Error: failed to write to target
main.c:20: Error: Execution failed
```

I then checked and found that `~/.config/light` is empty! What do I do now? What could've caused this? Please help, I can't seem to figure this out, and I use light on a daily basis! Thanks!

**Comment by haikarainen** [comment]
This is a permission issue for sysfs. The error about the config folder is expected behaviour if you dont have a minimum cap set and you have verbosity on. Read the README on permissions and come back if you still have issues!

**Comment by cubetastic33** [comment]
I checked the arch wiki page about backlight, and followed the instructions there to give users with the `video` group permissions to set the backlight by setting the value in `/sys/class/backlight/intel_backlight/brightness`, and then added my user to the video group, and logged out and logged back in. Now light works too! What I don't get is how light worked all this while and only recently stopped working. Do you have any idea why?

**Comment by haikarainen** [comment]
No idea buddy! There are some different methods to achieve permissions.

**Comment by loumray** [comment]
Same issue here, same fix. I am also wondering how come light was working without the proper permissions set on my system and then after latest upgrade it stopped working and force me to set the permissions properly. Anyway, glad it works again now. Thank you for raising this issue, it was helpful for me.

**Comment by maximbaz** [comment]
It was working before because we were setting suid on the binary, but recently someone pointed out that we should switch to the udev rules instead: https://bugs.archlinux.org/task/63493

Glad you managed to find the solution, I also put it in the [commit message](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/light&id=3f3b5d2b66b5bb0eff85aac8d95d098f3577b86e) as well in the comment solving the feature request.
