### ISSUE TITLE
Light 1.2-3 doesn't work 

### ISSUE THREAD

**Issue by atomheartother** [haikarainen/light#94]
Hello,

The latest upgrade of the `light` package on Arch linux, `1.2-3` (September 1st 2019 build) is broken my machine. Neither the backlight keys nor any of the the `light` commands actually modify the `/sys/class/backlight/...` files on my computer, as far as I can tell.

Downgrading to `1.2-2` (December 2nd 2018 build) immediately fixes the issue.

Here's the logs from `light -v 3` on a simple command:

```
~|⇒ light -v 3 -S 100
helpers.c:21: Error: could not open '/home/navenn_t/.config/light/targets/sysfs/backlight/auto/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
helpers.c:45: Error: could not open '/sys/class/backlight/intel_backlight/brightness' for writing
helpers.c:45: Error: Verify it exists with the right permissions
impl/sysfs.c:133: Error: failed to write to sysfs device
light.c:695: Error: failed to write to target
main.c:20: Error: Execution failed
```

**Comment by atomheartother** [comment]
For the record, `/sys/class/backlight/intel_backlight/brightness` exists.

I'm not sure where `light` gets the idea that `/home/navenn_t/.config/light/targets/sysfs/backlight/auto/minimum` exists though, there is a "light" folder in my config folder but it is empty.

**Comment by gregdan3** [comment]
Here to second this.

```
[15:01:58] gregdan3 :: Zendikar $ light -v 3 -S 15
helpers.c:45: Error: could not open '/sys/class/backlight/intel_backlight/brightness' for writing
helpers.c:45: Error: Verify it exists with the right permissions
impl/sysfs.c:133: Error: failed to write to sysfs device
light.c:695: Error: failed to write to target
main.c:20: Error: Execution failed
```

**Comment by m4thayus** [comment]
As per the [commit message ](https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/light) the udev rule in the build has been changed and now requires the user be a part of the 'video' group. Doing this fixed the issue for me. Follow the [wiki](https://wiki.archlinux.org/index.php/Users_and_groups#Other_examples_of_user_management) for how to do so.

**Comment by haikarainen** [comment]
As @m4thayus states above. Please check distro packages before creating an upstream issue.

**Comment by duncanam** [comment]
Just in case any others wander across this, @m4thayus's fix worked perfectly on my i3 Arch install. If you're flustered, this was quite easy and can be done simply via sudo/root:

`# usermod -aG video username`

You'll then need to restart your machine (or perhaps just logout) to see this work as expected.

**Comment by haikarainen** [comment]
Really, anyone wandering across this should just read the README.md

**Comment by atomheartother** [comment]
```
~|⇒ groups
bumblebee wireshark docker video wheel navenn_t
~|⇒ light -v 3 -S 100
helpers.c:21: Error: could not open '/home/navenn_t/.config/light/targets/sysfs/backlight/auto/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
helpers.c:45: Error: could not open '/sys/class/backlight/intel_backlight/brightness' for writing
helpers.c:45: Error: Verify it exists with the right permissions
impl/sysfs.c:133: Error: failed to write to sysfs device
light.c:695: Error: failed to write to target
main.c:20: Error: Execution failed```

Issue is not fixed.

**Comment by haikarainen** [comment]
@atomheartother For the love of god..

# This is not the place to discuss this. Your system is broken. Not light. Read the README.md to figure out what you need to do to your system to give light permission to sysfs. 

You probably dont have udev rules setup properly.
