### ISSUE TITLE
Unable to set brightness after update

### ISSUE THREAD

**Issue by iamrobox001** [haikarainen/light#95]
![1567579365](https://user-images.githubusercontent.com/38200989/64231931-612f5980-cee0-11e9-8cfb-4d9ad7e7ef4d.png)

Here is the verbose version and errors I get:
```
[ranger@BlueRingedOctopus ~]$ light -S 100 -v 3
helpers.c:21: Error: could not open '/home/ranger/.config/light/targets/sysfs/backlight/auto/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions
helpers.c:45: Error: could not open '/sys/class/backlight/intel_backlight/brightness' for writing
helpers.c:45: Error: Verify it exists with the right permissions
impl/sysfs.c:133: Error: failed to write to sysfs device
light.c:695: Error: failed to write to target
main.c:20: Error: Execution failed
```
Version of light: 1.2-3 installed from Arch community repository: [This](https://www.archlinux.org/packages/community/x86_64/light/)
Using sudo/root I can change the brightness.

**Comment by yuvadm** [comment]
Happened to me as well, this isn't an upstream issue -

```
$ ls -laH /sys/class/backlight/intel_backlight/brightness 
-rw-rw-r-- 1 root video 4096 Sep  4 11:56 /sys/class/backlight/intel_backlight/brightness
```

Adding your user to the `video` group should solve the problem.

**Comment by haikarainen** [comment]
This is like the fourth issue about this in a few days. Please read the readme and dont report distro bugs to upstream!
