### ISSUE TITLE
READ BEFORE YOU CREATE AN ISSUE: Arch package is broken

### ISSUE THREAD

**Issue by haikarainen** [haikarainen/light#96]
An arch package (not sure if official or AUR) is broken after an update. If you get this problem, just add your user to the video group. 

### Do not create new issues about this!

**Comment by C0rn3j** [comment]
Official package switched from setuid to udev.

https://bugs.archlinux.org/task/63621

**Comment by ti-mo** [comment]
It's not so visible in the issue tracker link above, but Arch users need to add their system user to the `video` group (`usermod -aG video <your-user>`). Don't forget to log out of your desktop session for these changes to apply.

**Comment by synthead** [comment]
Thank you for creating this issue!  Adding myself to the `video` group worked great!

**Comment by maximbaz** [comment]
As was already suggested on the Arch bug tracker, I added an install notice to the package as well, so hopefully nobody will have to go to this repo to find this ticket anymore 🙂

**Comment by xEnVrE** [comment]
Hi everybody, I updated to the latest version of `light` but still not able to use it properly even after adding myself to the `video` group and logging out/logging in.

Any suggestion?

**Comment by brettinternet** [comment]
@xEnVrE I did have to restart instead of merely logging in/out.

Verify your user is in the `video` group with:

```sh
getent group | grep <username>
```

**Comment by tom-on-the-internet** [comment]
In case this helps anyone:
I had to add my user to the `input` group to be able to change the keyboard back light.

**Comment by lbesnard** [comment]
I got the https://github.com/haikarainen/light/releases/download/v1.2/light_1.2_amd64.deb version on linux mint.

adding my user to both input/video and restarting didn't do a thing. I have to sudo to change the light. Maybe a different group name for debian base?

**Comment by JoshMcguigan** [comment]
I can confirm adding myself to the `video` group and restarting solved the issue for me on arch.

**Comment by GreyHat2** [comment]
Hello, I added my user to the `video` group but it still won't change my brightness, I'm on manjaro kde

**Comment by sloorush** [comment]
Can someone please mention this in the readme with the arch installation guide? It took my a lot of searching and then I landed on this issue 😅

**Comment by C0rn3j** [comment]
> Can someone please mention this in the readme with the arch installation guide? It took my a lot of searching and then I landed on this issue sweat_smile

https://wiki.archlinux.org/title/Backlight#Backlight_utilities

**Comment by sloorush** [comment]
> > Can someone please mention this in the readme with the arch installation guide? It took my a lot of searching and then I landed on this issue sweat_smile
> 
> https://wiki.archlinux.org/title/Backlight#Backlight_utilities

Maybe we can just add  "Arch users need to add their system user to the `video` group (`usermod -aG video <your-user>`)" so it is easier to find. This is also kind of tough to find 😅

**Comment by haikarainen** [comment]
It was already in the readme, but I added a clarifying statement under the Arch install section. 

Back in the day you needed to have a lot of elbow grease to even install Arch, i.e., be able to read a readme file before opening/commenting on issues. Not sure if that's still the case as I haven't touched it in a few years now (primarily due to wiki mods/higher-up community members being complete degenerates). Hopefully the arch community can improve and get back to what it used to be, because it was a _really_ good distro back in the day.
