### ISSUE TITLE
Clear Linux + Lenovo T520 > Not working

### ISSUE THREAD

**Issue by 0xA1B2** [haikarainen/light#97]
Hello,

I use Clear Linux on an older Lenovo T520 notebook. External HDMI monitor is connected, too.
Brightness of the notebook LCD does not change .. but that seems to be a path issue ?

Install was done this way from master:

> tar xf light-master.zip
> cd light-master
> ./autogen.sh
> ./configure --with-udev && make
> sudo make install

usermod -a -G video keks
reboot

> keks@t520/ $ light -L
> Listing device targets:
> 	sysfs/backlight/acpi_video0
> 	sysfs/backlight/auto
> 	sysfs/leds/platform::mute
> 	sysfs/leds/phy0-led
> 	sysfs/leds/tpacpi::thinklight
> 	sysfs/leds/tpacpi::power
> 	sysfs/leds/tpacpi::standby
> 	sysfs/leds/tpacpi::thinkvantage
> 	sysfs/leds/mmc0::
> 	sysfs/leds/platform::micmute
> 	util/test/dryrun

Command:

sudo light -S 50 -s sysfs/backlight/acpi_video0 -v 3

Results in:

helpers.c:21: Error: could not open '/etc/light/targets/sysfs/backlight/acpi_video0/minimum' for reading
helpers.c:21: Error: Verify it exists with the right permissions

However /etc/light is empty ..

I can locate acpi_video0 in: 
sys/class/backlight
sys/devices and some other locations (/var, /sys, /run).

In /sys/class/backlight/acpi_video0 there is no minimum file, only:

actual_brightness
brightness
max_brightness
(and bi_power, type, uevent)

**Comment by haikarainen** [comment]
Glad to hear that you resolved the issue.
